name: IKEA JSON Stock Checker
on:
  schedule:
    - cron: '0 5 * * *'   # 08:00 TR
    - cron: '0 9 * * *'   # 12:00 TR
    - cron: '0 13 * * *'  # 16:00 TR
    - cron: '0 17 * * *'  # 20:00 TR
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run JSON checker
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL:  ${{ secrets.TO_EMAIL }}
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          SUMMARY_EMAIL_ON_EMPTY: ${{ secrets.SUMMARY_EMAIL_ON_EMPTY }}
        run: |
          python availability_checker.py
